[variables]
PLAYWRIGHT_BROWSERS_PATH = "/app/pw-browsers"

[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["npm install", "npx playwright install chromium"]

[start]
cmd = "node server.mjs"
